services:
  invoice:
    restart: unless-stopped
    build:
      context: .
      dockerfile: base-dockerfile
    healthcheck:
      test: wget http://localhost:8080/graphiql || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    depends_on:
      invoice-db:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://invoice-db:27017
  invoice-db:
    image: mongo
    volumes:
      - invoice-db-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
  invoice-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "--app-id",
        "invoice",
        "--app-port",
        "${EXPERIMENT_CONFIG_SIDECAR_PORT:-8080}",
        "--app-protocol",
        "http",
        "--dapr-http-port",
        "3500",
        "-placement-host-address",
        "placement:50006",
        "--config",
        "/config.yaml",
        "--resources-path",
        "/components",
      ]
    network_mode: "service:invoice"
volumes:
  invoice-db-data:
